### PR TITLE
Better subway wagon textures & livery paint capability

### PR DESCRIPTION
**Pull request by Montandalar**
Add some good texture to the subway wagons. The default yellow colour will stay, but new colours can also be applied on top of a a grey base texture with the bike painter like the E231. Screenshots follow.

bettersubway_spread
screenshot_20210119_200831

### CODE REVIEW

**Comment by W3RQ01** [comment]
Really nice job +1, Where i can download they?

**Comment by Montandalar** [comment]
If you're a git user: after you clone this repository you can checkout the `bettersubway` branch. You can even add it as a separate remote:
`git remote add montandalar https://github.com/Montandalar/advtrains/ && git fetch -a montandalar && git checkout bettersubway`

If you're not interested in using git: [here](https://github.com/Montandalar/advtrains/archive/bettersubway.zip).

BTW, You can always download branches on GitHub like downloading the master branch; you just have to change branches first.

**Comment by W3RQ01** [comment]
Thx (I'm Dario23)

**Comment by W3RQ01** [comment]
Wow ahah amazing, now are really subway wagons :D

**Comment by Montandalar** [comment]
With the removal of the subway module and others into basic_trains, this PR will have to be made against that modpack in that repo instead.

**Comment by Montandalar** [comment]
Now lives [here](https://github.com/Montandalar/basic_trains/pull/1)

**Pull request closed without merging**
